### ISSUE TITLE
Cannot install cloned repo

### ISSUE THREAD

**Issue by orangedrink** [peoplewareDo/generator-ng2-seed-advanced#2]
Trying to do some work on this. Hope someone doesn't mind giving me a little help. 

When I try to npm install the cloned repo I get:
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/angular2-seed-advanced

So I changed my package.json file to read:
"angular2-seed-advanced":"NathanWalker/angular2-seed-advanced",

This should load the dependency from the correct repo as far as I know and seem to work but now I get an error on the angular2-seed-advanced postinstall:
npm ERR! Failed at the angular2-seed-advanced@0.0.0 postinstall script 'typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js'.

If I just try to 'typings install' I get an error about a missing typings.json file so I think that's the cause.

Am I doing this right and what do I need to do to make it work?

**Comment by victorsosa** [comment]
yes because I don't have angular2-seed-advanced or peoplewareDo/angular2-seed-advanced yet in the npm repo yet, give some time to fix that.

Don't point to NathanWalker/angular2-seed-advanced, please use https://github.com/peoplewareDo/angular2-seed-advanced (some changes goes there)

Workaround:
1. download https://github.com/peoplewareDo/angular2-seed-advanced
2. use npm link in a package folder will create a globally-installed symbolic link
3. download this https://github.com/peoplewareDo/generator-ng2-seed-advanced
4. inside the generator-ng2-seed-advanced run npm link angular2-seed-advanced to complete the dependency.

GOOD to go.

**Comment by orangedrink** [comment]
I'll do this. Thank youuu!

**Comment by victorsosa** [comment]
remember that when I publish the project on npm then you need to redownload the projects

**Comment by orangedrink** [comment]
Ok. Should be easy at that point. Thanks again!
